### ISSUE TITLE
can't find sender.java or jar

### ISSUE THREAD

**Issue by ggggsc** [hsnotebook/orabbix4zabbix4#2]
[root@zabbix2019-proxy02 orabbix]# ls
conf  doc  init.d  install.cmd  lib  logs  orabbix-1.2.3.jar  orabbix4zabbix4-master  orabbix.exe  orabbixw.exe  run.bat  run.sh  template  uninstall.cmd
[root@zabbix2019-proxy02 orabbix]# cd orabbix4zabbix4-master/
[root@zabbix2019-proxy02 orabbix4zabbix4-master]# ls
build.sh  dist  Dockerfile  orabbix  README.md  src
[root@zabbix2019-proxy02 orabbix4zabbix4-master]# chmod =x build.sh 
[root@zabbix2019-proxy02 orabbix4zabbix4-master]# ./build.sh 
clean dist
compile Sender.java
./build.sh:行7: javac: 未找到命令
add Sender.class to jar file
./build.sh:行14: jar: 未找到命令
build image
./build.sh:行21: docker: 未找到命令
[root@zabbix2019-proxy02 orabbix4zabbix4-master]# find / -name sender.java
[root@zabbix2019-proxy02 orabbix4zabbix4-master]#

**Comment by hsnotebook** [comment]
需要安装jdk 和 docker
